export default {

    type: [
        ["Balade","WALK"],
        ["Danse","DANSE"],
        ["Insolite","UNUSUAL"],
        ["Manifestation commerciale","COMMERCIAL"],
        ["Sports et loisirs","SPORT_AND_LEISUR"],
        ["Musique","MUSIC"],
        ["Nature et détente","NATURE_AND_RELAXATION"],
    ],

    category: [
        ["Balade","WALK"],
        ["Animations","ANIMATIONS"],
        ["Visites guidées","GUIDED_TOURS"],
        ["Spectacle","SPECTACLE"],
        ["Festival","FESTIVAL"],
        ["Concert","CONCERT"],
        ["Cinéma","CINEMA"],
        ["Récital","RECITAL"],
        ["Rencontres","ENCOUNTERS"],
        ["Portes ouvertes","OPEN_HOUSE"],
        ["Opéra","OPERA"],
        ["Exposition","EXHIBITION"],
        ["Foire ou salon","FAIR_OR_EXHIBITION"],
        ["Théâtre","THEATER"],
        ["Brocante","FLEA_MARKET"],
        ["Marché","MARKET"],
        ["Sport","SPORT"],
    ],

    theme: [
        ["Musée","MUSEE"],
        ["Danse","DANSE"],
        ["Vidéo","VIDEO"],
        ["Vin - oenologie","VIN"],
        ["Sports nautiques","NAUTIC_SPORT"],
        ["Pop musique (rock...)","MUSIC_POP"],
        ["Musique classique","MUSIC_CLASSIC"],
        ["Musique de variété","MUSIC_VARIETY"],
        ["Jazz et blues","JAZZ"],
        ["Mode","MODE"],
        ["Littérature","LITERATURE"],
        ["Jeune public","YOUNG_AUDIENCE"],
        ["Historique","HISTORIC"],
        ["Gastronomie","GASTRONOMIE"],
        ["Fleurs Plantes","PLANTS"],
        ["Comique","COMIC"],
        ["Cinéma","CINEMA"],
        ["Bio","BIO"],
        ["Artisanat","ARTISANAT"],
        ["Art contemporain","CONTEMPORARY_ART"],
        ["Photographie","PHOTO"],
    ]

}